sonar.projectKey=boekenwurmen_boekenwurmen-frontend
sonar.organization=boekenwurmen

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.svelte.test.js,**/*.svelte.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
